### ISSUE TITLE
This example is not working as expected.

### ISSUE THREAD

**Issue by kethan** [yeapjs/yeap#13]
https://stackblitz.com/edit/vitejs-vite-jwkcxz?file=main.jsx&terminal=dev

**Comment by hanako-eo** [comment]
what is the expected result ?

**Comment by kethan** [comment]
The expected result is that node b renders to [1, 2, 3]

**Comment by hanako-eo** [comment]
Thanks for reporting this, I will see why the reactivity is lost, and I will push the correctif for the version 1.1.0

**Comment by hanako-eo** [comment]
### Why your example doesn't work
The problem is from the impossibility to use a function in the initial value.

### So why doesn't it work when I don't use a function (but HTML elements) ?
In internal, want you're created an element you use `h` (transpile to h with JSX transpiler), but to use the context and the conditions, we needed to use a function (because we don't use VDOM), if you want to test it, try this code:

```jsx
import { h } from "yeap/web";

const App = (
  <div>
    Hello <b>World</b>!
  </div>
);

document.body.append(App());
```

Warning: a component who has the possibility to be unmounted (in the 1.0, it's all components) return a reactor 
```jsx
function App() {
  return <div>Hello World!</div>;
}

const app = <App />;

document.body.append(app()());
```
